filegroup(
    name = "cc",
    srcs = ["cc.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "c",
    srcs = ["c.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "cc_embed_binary",
    srcs = ["cc_embed_binary.build_defs"],
    visibility = ["PUBLIC"],
)
