export_file(
    name = "arch",
    src = "arch.build_defs",
    visibility = [
        "//package/...",
        "//third_party/go/...",
    ],
)

filegroup(
    name = "cc",
    srcs = ["cc.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "c",
    srcs = ["c.build_defs"],
    visibility = ["PUBLIC"],
)
