VERSION="1.0.3"

remote_file(
    name = "arcat",
    url = f"https://github.com/please-build/arcat/releases/download/v{VERSION}/arcat-{VERSION}-{CONFIG.OS}_{CONFIG.ARCH}",
    binary = True,
    visibility = ["PUBLIC"],
)
